accounts/urls.py
from django.urls import path, include
from . import views


app_name = 'accounts'

urlpatterns = [
    path('register/',views.UserRegisterView.as_view(),name='register'),
    path('edit_profile/',views.UserEditView.as_view(),name='edit_profile'),
    path('password/',views.PasswordsChangeView.as_view(),name='password_change'),
    path('password_success/',views.password_success,name='password_success'),   
    path('<int:pk>/profile/',views.ShowProfilePageView.as_view(),name='show_profile'), 
    path('<int:pk>/edit_profile_page/',views.EditProfilePageView.as_view(),name='edit_profile_page'),  
 
      
     
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('',views.ListPostsView.as_view(),name='posts'),
    path('article/<int:pk>',views.DetailPostView.as_view(),name='article-detail'),
    path('add_post',views.AddPostView.as_view(),name='add_post'),
    path('article/edit/<int:pk>',views.UpdatePostView.as_view(),name='update_post'),
    path('article/delete/<int:pk>',views.DeletePostView.as_view(),name='delete_post'),
    #path('add_category',views.AddCategoryView.as_view(),name='add_category'),
    #path('category/<str:cats>',views.category,name='category'),
    path('like/<int:pk>',views.Likeview,name='like_post'),
    path('article/<int:pk>/comment/',views.AddCommentView.as_view(),name='add_comment'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('accounts/',include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('',include('blog.urls',namespace='blog')),
    path('',include('accounts.urls')),
]

urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models 
from django.contrib.auth.models import User
from django.urls import reverse   
from ckeditor.fields import RichTextField
from django.db.models.signals import post_save
from django.dispatch import receiver


# create your views here 

class Post(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    title = models.CharField(max_length=70)
    description = models.CharField(max_length=277)
    #body = models.TextField() 
    body = RichTextField(blank=True,null=True)
    img = models.ImageField(blank=True,null=True,upload_to='images/')
    created_at = models.DateTimeField(auto_now=True)
    category = models.ForeignKey('Category',on_delete=models.CASCADE)
    likes = models.ManyToManyField(User,related_name='likes')
    
    def total_likes(self):
        return self.likes.count()
    
    def __str__(self):
        return self.title + ' | ' + str(self.author)
     
    def get_absolute_url(self):
        return reverse('blog:article-detail', args=[str(self.id)]) 
    
    
class Category(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('blog:posts') 
    
class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    bio = models.TextField() 
    profile_pic = models.ImageField(upload_to="profile_pic",null=True,blank=True)
    webiste_url = models.CharField(max_length=70,null=True,blank=True)
    facebook_url = models.CharField(max_length=70,null=True,blank=True)
    instagram_url = models.CharField(max_length=70,null=True,blank=True)
    


    def __str__(self):
        return str(self.user)



    
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance) 
        
        
class Comment(models.Model):
    post = models.ForeignKey(Post,related_name='comments',on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    body = models.TextField()
    date_added = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return '%s - %s' % (self.post.title,self.name)

    
    
    

blog/views.py
from django.shortcuts import get_object_or_404, render
from .models import Post, Category, Comment
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect
# Create your views here.

def Likeview(request, pk):
    post = get_object_or_404(Post,id=request.POST.get('post_id'))
    liked = False 
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        liked = False 
    else:
        post.likes.add(request.user) 
        liked = True
    return HttpResponseRedirect(reverse('blog:article-detail', args=[str(pk)]))

class ListPostsView(ListView):
    model = Post
    template_name = 'home.html'
    context_object_name = 'posts'
    ordering = ['-created_at']
    
class DetailPostView(DetailView):
    model = Post
    template_name = 'detail.html'
    context_object_name = 'post' 

    def get_context_data(self, **kwargs):
        total = get_object_or_404(Post,id=self.kwargs['pk'])
        
        liked = False
        if total.likes.filter(id=self.request.user.id).exists():
            liked = True
    
        total_likes = total.total_likes()
        context = super(DetailPostView,self).get_context_data(**kwargs)
        context["total_likes"] = total_likes
        context["liked"] = liked
        return context
    

class AddPostView(CreateView):
    model = Post 
    template_name = 'add_post.html'
    fields = ['title','description','body','img','category']
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(AddPostView, self).form_valid(form)
    

class UpdatePostView(UpdateView):
    model = Post 
    template_name = 'update_post.html'
    fields = ['title','description','body','category']
   

class DeletePostView(DeleteView):
    model = Post 
    template_name = 'delete_post.html'
    success_url = reverse_lazy('blog:posts')
    
#class AddCategoryView(CreateView):
#    model = Category 
#    template_name = 'add_category.html'
#    fields = '__all__'

#def category(request, cats):
#    category_posts = Post.objects.filter(category=cats)
#    return render(request, 'categories.html', {'category_posts':category_posts})


class AddCommentView(CreateView):
    model = Comment 
    template_name = 'add_comment.html'
    fields = ['name','body']
    
    def get_success_url(self):
        return reverse('blog:article-detail', args=[str(self.kwargs['pk'])])
    
    
    def form_valid(self, form):
        form.instance.post_id = self.kwargs['pk']
        return super(AddCommentView, self).form_valid(form)
    
    

blog/templates/add_category.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
{% if user.is_authenticated %}
<h2>Add category</h2>
<br><br><br>
<form method="POST">
 
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">Add category</button>
    {% endbuttons %}

{% else %}
you are not allowed here

{% endif %}
{% endblock body %}

blog/templates/add_comment.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
{% if user.is_authenticated %}
<h2>Add comment</h2>
<br><br><br>
<form method="POST" enctype="multipart/form-data">
 
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">Add Comment</button>
    {% endbuttons %}

{% else %}
you are not allowed here

{% endif %}
{% endblock body %}

blog/templates/add_post.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
{% if user.is_authenticated %}
<h2>Add Post</h2>
<br><br><br>
<form method="POST" enctype="multipart/form-data">
 
    {% csrf_token %}
    {% bootstrap_form form %}
    {{form.media}}
    
    {% buttons %}
        <button type="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}

{% else %}
you are not allowed here

{% endif %}
{% endblock body %}

blog/templates/categories.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
  
  {% for post in category_posts %}
    <h1> Category {{post.category}} <h1>
    <br>
    <h2 class="post-title">
      <a href="#">{{post.title}}</a>
    </h2>
    <p class="lead">
      by {{post.author}}  
      {% if user.is_authenticated %} 
      - <a class="btn btn-default" href="{% url 'blog:update_post' post.id %}">Edit</a> 
      - 
      <a class="btn btn-danger" href="{% url 'blog:delete_post' post.id %}">Delete</a>
      {% endif %}
    </p>
    <p><span class="glyphicon glyphicon-time"></span> Posted on August 28, 2013 at 10:00 PM</p>
    <p>{{post.description}}.</p>
    <a class="btn btn-default" href="{% url 'blog:article-detail' post.id %}">Read More</a>
    <br><br><br><br>
    <hr>

  {% empty %}
  there is no catergories
  {% endfor %}

          
{% endblock body %}

blog/templates/delete_post.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
{% if user.is_authenticated %}
<h1>Delete Post</h1>
<br><br><br>
<form method="POST">
    {% csrf_token %}
    <h3>Are you sure do you want to delete {{post.title}}? </3>
    <br><br>

    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">Delete</button>
    {% endbuttons %}


{% else %}
you are not allowed here
    
{% endif %}

{% endblock body %}

blog/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <!-- Page Content -->
    <div class="container">

      <div class="row">

        <!-- Blog Post Content Column -->
        <div class="col-lg-12">

          <!-- Blog Post -->

          <!-- Title -->
          <h1 class="post-title">{{post.title}}</h1>

          <!-- Author -->
          <p class="lead">
            by {{post.author}} 
            {% if user.is_authenticated %}
              {% if user.id == post.author.id %}
              - <a class="btn btn-default" href="{% url 'blog:update_post' post.id %}">Edit</a> - 
              <a class="btn btn-danger" href="{% url 'blog:delete_post' post.id %}">Delete</a>
              {% endif %} 
            {% endif %}
          </p>

          <hr>

          <!-- Date/Time -->
          <p><span class="glyphicon glyphicon-time"></span> Posted on {{post.created_at}}</p>

          <hr>

          <!-- Post Content -->
          {% if post.img %}
          <img src="{{post.img.url}}">
          {% endif %}
          <br><br>
          {{post.body|safe}}

          <hr>

          <a class="btn btn-default" href="{% url 'blog:posts'%}">Go Back</a>
          <br><br>
          <form action="{% url 'blog:like_post' post.id %}" method="POST" >
            {% csrf_token %}
          {% if user.is_authenticated %}  
            {% if liked %}
              <button type="submit" name="post_id" value="{{post.id}}" class="btn btn-danger btn-sm"> Unlike </button>

            {% else %}
              <button type="submit" name="post_id" value="{{post.id}}" class="btn btn-primary btn-sm"> Like </button>
              {% endif %}
          {% else %}
            <small> login to like <a href="{% url 'login'%}">Login</a></small>
          {% endif %}
          - {{ total_likes }} Likes

          <br>
          <form>
          <hr>
          <div class="card mb-3" >
            <div class="row g-0">
              <div class="col-md-2">
                {% if post.author.profile.profile_pic %}
                  <img src="{{post.author.profile.profile_pic.url}}" class="img-fluid rounded-start" alt="..." width=100 height=200>
                {% else %}
                  <img src="{% static 'images/defalt_pic.jpg' %}" class="img-fluid rounded-start" alt="..." width=100 height=100>
                {% endif %}
              </div>
              <div class="col-md-10">
                <div class="card-body">
                  <h5 class="card-title">{{post.author}}</h5>
                  <p class="small text-muted">
                    <a href="{% url 'accounts:show_profile' post.author.profile.id %}">Profile page</a> | 
                    {% if post.author.profile.website_url %}
                    <a href="{{post.author.Profile.website_url}}">Website | </a>
                    {% endif %}
                    {% if post.author.profile.facebook_url %}
                    <a href="{{post.author.profile.facebook_url}}"> facebook | </a>
                    {% endif %}
                    {% if post.author.profile.instagram_url %}
                    <a href="{{post.author.profile.instagram_url}}"> instagram</a>
                    {% endif %}
                  </p>

                  <p class="card-text">{{post.author.profile.bio}}.</p>
                  <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                </div>
              </div>
            </div>
          </div>
          <hr> 
          <!-- Blog Comments -->

          <hr>
          <h2>Comments</h2>
          
          {% if not post.comments.all %}
            No comments Yet..<a href="{% url 'blog:add_comment' post.pk %}">Add Comment</a>
          
          {% else %}
            <a href="{% url 'blog:add_comment' post.pk %}">Add Comment</a>
            <br><br>
            {% for comment in post.comments.all  %}
              <strong>{{ comment.name }} - 
              {{comment.date_added}}</strong>
              <br>
              {{comment.body}}
              <br><br>
              
            
            {% endfor %}
            <hr>
          
          {% endif %}

      
          <hr>
    </div>

{% endblock body %}
  

blog/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <!-- Page Content -->
    {% if user.is_authenticated %} 
      <p>Profile information:<p>
      <ul class=" navbar-nav ml-auto">
    
          {% if user.profile.id %}
            <li>
              <a href="{% url 'accounts:show_profile' user.profile.id %}">{{user.username}} 
              </a>
            </li>
          {% endif %}
          <br>
          <li>
            <a href="{% url 'accounts:show_profile' user.profile.id %}">Show Profile Page</a>
          </li>
        {% endif %}
      </ul>
    <div class="container">

      <div class="row">

        <!-- Blog Entries Column -->
        <div class="col-md-12">

          <!-- First Blog Post -->
          {% for post in posts  %}
          <h2 class="post-title">
            <a href="#">{{post.title}}</a>
          </h2>
          <p class="lead">
            by {{post.author}}  
            {% if user.is_authenticated %} 
              {% if user.id == post.author.id %}
              - <a class="btn btn-default" href="{% url 'blog:update_post' post.id %}">Edit</a> 
              - 
              <a class="btn btn-danger" href="{% url 'blog:delete_post' post.id %}">Delete</a>
              {% endif %}
            {% endif %}
          </p>
          <p><span class="glyphicon glyphicon-time"></span> Posted on {{post.created_at}}</p>
          <p>{{post.description}}.</p>
          <a class="btn btn-default" href="{% url 'blog:article-detail' post.id %}">Read More</a>
          <br><br><br><br>
          <hr>

          {% endfor %}





        
          
{% endblock body %}

blog/templates/update_post.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
{% if user.is_authenticated %}
    {% if user.id == post.author.id %}
        <h2>Update Post</h2>
        <br><br><br>
        <form method="POST">
        
            {% csrf_token %}
            {% bootstrap_form form %}
            {{form.media}}
            {% buttons %}
                <button type="submit" class="btn btn-primary">Submit</button>
            {% endbuttons %}
    {% else %}  
        your not allowed here
    {% endif %}
{% else %}
    your not allowed here


{% endif %}

{% endblock body %}