accounts/urls.py
from django.urls import path, include
from . import views


app_name = 'accounts'

urlpatterns = [
    path('register/',views.UserRegisterView.as_view(),name='register'),
    path('edit_profile/',views.UserEditView.as_view(),name='edit_profile'),
    path('password/',views.PasswordsChangeView.as_view(),name='password_change'),
    path('password_success/',views.password_success,name='password_success'),   
    path('<int:pk>/profile/',views.ShowProfilePageView.as_view(),name='show_profile'), 
    path('<int:pk>/edit_profile_page/',views.EditProfilePageView.as_view(),name='edit_profile_page'),  
 
      
     
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('',views.ListPostsView.as_view(),name='posts'),
    path('article/<int:pk>',views.DetailPostView.as_view(),name='article-detail'),
    path('add_post',views.AddPostView.as_view(),name='add_post'),
    path('article/edit/<int:pk>',views.UpdatePostView.as_view(),name='update_post'),
    path('article/delete/<int:pk>',views.DeletePostView.as_view(),name='delete_post'),
    #path('add_category',views.AddCategoryView.as_view(),name='add_category'),
    #path('category/<str:cats>',views.category,name='category'),
    path('like/<int:pk>',views.Likeview,name='like_post'),
    path('article/<int:pk>/comment/',views.AddCommentView.as_view(),name='add_comment'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('accounts/',include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('',include('blog.urls',namespace='blog')),
    path('',include('accounts.urls')),
]

urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Home - Simple Blog Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css'%}"rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/simple-blog-template.css'%}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'blog:posts'%}">Simple Blog</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li>
                <!--<a href="#">Add Category</a>-->
              </li>
              <li>
                <a href="{% url 'blog:add_post'%}">add post</a>
              </li>
              <li>
                <a href="{% url 'accounts:edit_profile'%}">edit settings</a>
              </li>
              <li>
                <a href="{% url 'accounts:edit_profile_page' user.profile.id %}">Edit Profile Page</a>
              </li>
              <li>
                <a href="{% url 'logout'%}">Logout</a>
              </li>
            {% else %}
              <li>
                <a href="{% url 'login'%}">Login</a>
              </li>
              <li>
                <a href="{% url 'accounts:register'%}">Register</a>
              </li>
           
          </ul>
        </div>
          {% endif %}
        
        <!-- /.navbar-collapse -->
      </div>
      <!-- /.container -->
    </nav>

{% block body %}


{% endblock body %}



    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <p>Copyright &copy; Your Website 2022</p>
          </div>
          <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
      </div>
    </footer>


    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

  </body>

</html>